# Generated by Django 2.0 on 2018-09-08 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aarea', models.CharField(max_length=40, verbose_name='区域')),
                ('isdelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '区域',
                'verbose_name_plural': '区域字典',
            },
        ),
        migrations.CreateModel(
            name='CetagoryTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccetagory', models.CharField(max_length=40, verbose_name='类别')),
                ('isdelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '类别',
                'verbose_name_plural': '类别字典',
            },
        ),
        migrations.CreateModel(
            name='CompanyTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccompany', models.CharField(max_length=40, verbose_name='公司')),
                ('isdelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '公司',
                'verbose_name_plural': '公司字典',
            },
        ),
        migrations.CreateModel(
            name='DepartmentTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddepartment', models.CharField(max_length=40, verbose_name='部门')),
                ('isdelete', models.BooleanField(default=False)),
                ('dcetagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basedata.CetagoryTable', verbose_name='类别')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门字典',
            },
        ),
        migrations.CreateModel(
            name='FrameTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isdelete', models.BooleanField(default=False)),
                ('farea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basedata.AreaTable', verbose_name='区域')),
                ('fcompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basedata.CompanyTable', verbose_name='公司')),
                ('fdepartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basedata.DepartmentTable', verbose_name='部门')),
            ],
            options={
                'verbose_name': '构架体系',
                'verbose_name_plural': '构架体系',
            },
        ),
    ]
