# Generated by Django 2.0 on 2018-09-09 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeinfoTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eemployee_id', models.IntegerField(verbose_name='工号')),
                ('Ename', models.CharField(max_length=50, verbose_name='姓名')),
                ('Egender', models.BooleanField(choices=[('1', '女性'), ('0', '男性')], default=('1', '女性'), verbose_name='性别')),
                ('Eage', models.IntegerField(blank=True, verbose_name='年龄')),
                ('Emarita_status', models.CharField(blank=True, choices=[('married', '已婚'), ('unmarried', '未婚')], max_length=50, verbose_name='婚姻状态')),
                ('Ework_status', models.CharField(choices=[('on_the_job', '在职'), ('part_time_job', '兼职'), ('quit_job', '离职')], default=('on_the_job', '在职'), max_length=50, verbose_name='工作状态')),
                ('Estart_date', models.DateField(verbose_name='入职时间')),
                ('Eeducation', models.CharField(blank=True, choices=[('undergraduate', '本科'), ('specialty', '专科'), ('high school', '高中')], max_length=8, verbose_name='学历')),
                ('Egraduate_school', models.CharField(blank=True, max_length=40, verbose_name='毕业院校')),
                ('Egraduation_date', models.DateField(blank=True, verbose_name='毕业日期')),
                ('Estart_work_date', models.DateField(blank=True, verbose_name='开始工作日期')),
                ('Ehousehold_register', models.CharField(blank=True, max_length=20, verbose_name='户籍')),
                ('Enation', models.CharField(blank=True, max_length=20, verbose_name='民族')),
                ('Equit_date', models.DateField(blank=True, verbose_name='离职时间')),
                ('Eremarks', models.TextField(blank=True, max_length=1000, verbose_name='备注')),
                ('isdelete', models.BooleanField(default=0)),
            ],
            options={
                'verbose_name': '员工信息',
                'verbose_name_plural': '员工信息',
            },
        ),
        migrations.CreateModel(
            name='PositionTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pposition', models.CharField(max_length=50, verbose_name='职位')),
                ('isdelete', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WorkLevelTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wwork_level', models.CharField(max_length=50, verbose_name='工作级别')),
                ('isdelete', models.BooleanField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='employeeinfotable',
            name='Eposition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeinfo.PositionTable', verbose_name='职位'),
        ),
        migrations.AddField(
            model_name='employeeinfotable',
            name='Ework_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeinfo.WorkLevelTable', verbose_name='级别'),
        ),
    ]
