# Generated by Django 2.0 on 2018-09-10 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aarea', models.CharField(max_length=40, verbose_name='区域')),
                ('isdelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '区域',
                'verbose_name_plural': '区域字典',
            },
        ),
        migrations.CreateModel(
            name='CetagoryTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ccetagory', models.CharField(max_length=40, verbose_name='类别')),
                ('isdelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '类别',
                'verbose_name_plural': '类别字典',
            },
        ),
        migrations.CreateModel(
            name='CompanyTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ccompany', models.CharField(max_length=40, verbose_name='公司')),
                ('isdelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '公司',
                'verbose_name_plural': '公司字典',
            },
        ),
        migrations.CreateModel(
            name='DepartmentTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ddepartment', models.CharField(max_length=40, verbose_name='部门')),
                ('isdelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门字典',
            },
        ),
        migrations.CreateModel(
            name='EmployeeinfoTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eemployee_id', models.IntegerField(unique=True, verbose_name='工号')),
                ('Ename', models.CharField(max_length=50, unique=True, verbose_name='姓名')),
                ('Egender', models.CharField(choices=[('MM', '女性'), ('GG', '男性')], default=('MM', '女性'), max_length=50, verbose_name='性别')),
                ('Eage', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('Emarita_status', models.CharField(blank=True, choices=[('married', '已婚'), ('unmarried', '未婚')], max_length=50, verbose_name='婚姻状态')),
                ('Ework_status', models.CharField(choices=[('on_the_job', '在职'), ('part_time_job', '兼职'), ('quit_job', '离职')], default=('on_the_job', '在职'), max_length=50, verbose_name='工作状态')),
                ('Estart_date', models.DateField(verbose_name='入职时间')),
                ('Eeducation', models.CharField(blank=True, choices=[('undergraduate', '本科'), ('specialty', '专科'), ('high school', '高中')], max_length=50, verbose_name='学历')),
                ('Egraduate_school', models.CharField(blank=True, max_length=50, verbose_name='毕业院校')),
                ('Egraduation_date', models.DateField(blank=True, null=True, verbose_name='毕业日期')),
                ('Estart_work_date', models.DateField(blank=True, null=True, verbose_name='开始工作日期')),
                ('Equit_date', models.DateField(blank=True, null=True, verbose_name='离职时间')),
                ('Eremarks', models.TextField(blank=True, max_length=1000, null=True, verbose_name='备注')),
                ('Etel', models.CharField(blank=True, max_length=50, null=True, verbose_name='联系电话')),
                ('Eemergency_contact_person', models.CharField(blank=True, max_length=50, null=True, verbose_name='紧急联系人')),
                ('Eemergency_contact_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='紧急联系电话')),
                ('isdelete', models.BooleanField(default=0)),
                ('Earea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeinfo.AreaTable', verbose_name='区域')),
                ('Ecetagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeinfo.CetagoryTable', verbose_name='部门类别')),
                ('Ecompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeinfo.CompanyTable', verbose_name='公司')),
                ('Edepartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeinfo.DepartmentTable', verbose_name='部门')),
            ],
            options={
                'verbose_name': '员工资料',
                'verbose_name_plural': '员工资料',
            },
        ),
        migrations.CreateModel(
            name='HouseholdRegisterTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hhousehold_register', models.CharField(max_length=50, verbose_name='户籍')),
                ('isdelete', models.BooleanField(default=0)),
            ],
            options={
                'verbose_name': '户籍',
                'verbose_name_plural': '户籍字典',
            },
        ),
        migrations.CreateModel(
            name='NationTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nnation', models.CharField(max_length=50, verbose_name='民族')),
                ('isdelete', models.BooleanField(default=0)),
            ],
            options={
                'verbose_name': '民族',
                'verbose_name_plural': '民族字典',
            },
        ),
        migrations.CreateModel(
            name='PositionTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pposition', models.CharField(max_length=50, verbose_name='职位')),
                ('isdelete', models.BooleanField(default=0)),
            ],
            options={
                'verbose_name': '职位',
                'verbose_name_plural': '职位',
            },
        ),
        migrations.CreateModel(
            name='WorkLevelTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wwork_level', models.CharField(max_length=50, verbose_name='工作级别')),
                ('isdelete', models.BooleanField(default=0)),
            ],
            options={
                'verbose_name': '工作级别',
                'verbose_name_plural': '工作级别',
            },
        ),
        migrations.AddField(
            model_name='employeeinfotable',
            name='Ehousehold_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employeeinfo.HouseholdRegisterTable', verbose_name='户籍'),
        ),
        migrations.AddField(
            model_name='employeeinfotable',
            name='Enation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employeeinfo.NationTable', verbose_name='民族'),
        ),
        migrations.AddField(
            model_name='employeeinfotable',
            name='Eposition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeinfo.PositionTable', verbose_name='职位'),
        ),
        migrations.AddField(
            model_name='employeeinfotable',
            name='Ework_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeinfo.WorkLevelTable', verbose_name='级别'),
        ),
    ]
