# Generated by Django 2.0 on 2018-09-06 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CetagoryTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccetagory', models.CharField(max_length=40, verbose_name='类别')),
                ('carea', models.CharField(max_length=40, verbose_name='区域')),
                ('isdelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '类别',
                'verbose_name_plural': '类别字典',
            },
        ),
        migrations.CreateModel(
            name='DepartmentTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddepartment', models.CharField(max_length=40, verbose_name='部门')),
                ('isdelete', models.BooleanField(default=False)),
                ('dcetagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.CetagoryTable', verbose_name='类别')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门字典',
            },
        ),
    ]
