# Generated by Django 2.0 on 2018-08-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddepartment', models.CharField(max_length=40, verbose_name='部门')),
                ('dcetagory', models.CharField(max_length=40, verbose_name='类别')),
                ('disdelte', models.BooleanField()),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门字典',
            },
        ),
    ]
