# Generated by Django 2.0 on 2018-09-25 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employeeinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btitle', models.CharField(max_length=50, verbose_name='书名')),
                ('binfo', models.CharField(max_length=50, verbose_name='描述')),
            ],
        ),
        migrations.CreateModel(
            name='ContactsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_full_name', models.CharField(max_length=50, verbose_name='联系人')),
                ('fixed_telephone', models.CharField(blank=True, max_length=50, null=True, verbose_name='固定电话')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='手机号码')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('remarks', models.TextField(blank=True, max_length=1000, null=True, verbose_name='备注')),
                ('isdelete', models.BooleanField(default=0)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeinfo.AreaTable', verbose_name='区域')),
            ],
            options={
                'verbose_name': '联系人',
                'verbose_name_plural': '联系人',
            },
        ),
        migrations.CreateModel(
            name='FiberAndNetworkTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiber_number', models.CharField(max_length=50, verbose_name='光纤编号')),
                ('accounts', models.CharField(max_length=50, verbose_name='帐号')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('ip_addr', models.GenericIPAddressField(verbose_name='ip地址')),
                ('gateway', models.GenericIPAddressField(verbose_name='网关')),
                ('subnet_mask', models.GenericIPAddressField(verbose_name='子网掩码')),
                ('dns1', models.GenericIPAddressField(verbose_name='主DNS')),
                ('dns2', models.GenericIPAddressField(verbose_name='次DNS')),
                ('remarks', models.TextField(max_length=1000, verbose_name='备注')),
                ('isdelete', models.BooleanField(default=0)),
                ('bak1', models.BooleanField(default=0)),
                ('bak2', models.BooleanField(default=0)),
                ('bak3', models.BooleanField(default=0)),
                ('bak4', models.BooleanField(default=0)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeinfo.AreaTable', verbose_name='区域')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeinfo.CompanyTable', verbose_name='公司')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operationinfo.ContactsTable', verbose_name='联系人')),
            ],
            options={
                'verbose_name': '光纤网络',
                'verbose_name_plural': '光纤网络',
            },
        ),
        migrations.CreateModel(
            name='HardwareResourceLibratyTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fixed_assets_number', models.CharField(max_length=50, verbose_name='固定资产')),
                ('brand', models.CharField(max_length=50, verbose_name='品牌')),
                ('category', models.CharField(max_length=50, verbose_name='类型')),
                ('model', models.CharField(max_length=50, verbose_name='型号')),
                ('purchase_date', models.DateField(verbose_name='采购日期')),
                ('guarantee', models.DateField(verbose_name='保修日期')),
                ('service_code', models.CharField(max_length=50, verbose_name='服务代码')),
                ('cpu', models.CharField(max_length=50, verbose_name='cpu')),
                ('memory', models.CharField(max_length=50, verbose_name='内存')),
                ('hard_disk', models.CharField(max_length=50, verbose_name='硬盘')),
                ('remarks', models.TextField(max_length=1000, verbose_name='备注')),
                ('isdelete', models.BooleanField(default=0)),
                ('bak1', models.BooleanField(default=0)),
                ('bak2', models.BooleanField(default=0)),
                ('bak3', models.BooleanField(default=0)),
                ('bak4', models.BooleanField(default=0)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeinfo.AreaTable', verbose_name='区域')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeinfo.CompanyTable', verbose_name='公司')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeinfo.DepartmentTable', verbose_name='部门')),
            ],
            options={
                'verbose_name': '硬件资源库',
                'verbose_name_plural': '硬件资源库',
            },
        ),
        migrations.CreateModel(
            name='Heroinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(max_length=50, verbose_name='性别')),
                ('hbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operationinfo.Bookinfo', verbose_name='书名')),
            ],
            options={
                'verbose_name': '英雄',
                'verbose_name_plural': '英雄',
            },
        ),
        migrations.CreateModel(
            name='SoftResourceLibraryTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='软件类型')),
                ('sn', models.CharField(max_length=50, verbose_name='软件序号')),
                ('guarantee', models.DateField(verbose_name='保修期')),
                ('edition', models.CharField(max_length=50, verbose_name='软件版本')),
                ('purchase_date', models.DateField(verbose_name='采购日期')),
                ('remarks', models.TextField(max_length=1000, verbose_name='备注')),
                ('isdelete', models.BooleanField(default=0)),
                ('bak1', models.BooleanField(default=0)),
                ('bak2', models.BooleanField(default=0)),
                ('bak3', models.BooleanField(default=0)),
                ('bak4', models.BooleanField(default=0)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeinfo.AreaTable', verbose_name='区域')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeinfo.CompanyTable', verbose_name='公司')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeinfo.DepartmentTable', verbose_name='部门')),
            ],
            options={
                'verbose_name': '软件资源库',
                'verbose_name_plural': '软件资源库',
            },
        ),
        migrations.CreateModel(
            name='SupplierTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=50, verbose_name='供应商')),
                ('isdelete', models.BooleanField(default=0)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeinfo.AreaTable', verbose_name='区域')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
            },
        ),
        migrations.AddField(
            model_name='contactstable',
            name='supplier_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operationinfo.SupplierTable', verbose_name='供应商'),
        ),
    ]
